config/routes.rb
Rails.application.routes.draw do
  resources :order_menu_items
  resources :orders
  resources :menu_items
  resources :restaurants
  root 'restaurants#index'
end

app/models/order_menu_item.rb
class OrderMenuItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/controllers/order_menu_items_controller.rb
class OrderMenuItemsController < ApplicationController
  before_action :set_order_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /order_menu_items
  # GET /order_menu_items.json
  def index
    @order_menu_items = OrderMenuItem.all
  end

  # GET /order_menu_items/1
  # GET /order_menu_items/1.json
  def show
  end

  # GET /order_menu_items/new
  def new
    @order_menu_item = OrderMenuItem.new
  end

  # GET /order_menu_items/1/edit
  def edit
  end

  # POST /order_menu_items
  # POST /order_menu_items.json
  def create
    @order_menu_item = OrderMenuItem.new(order_menu_item_params)

    respond_to do |format|
      if @order_menu_item.save
        format.html { redirect_to @order_menu_item, notice: 'Order menu item was successfully created.' }
        format.json { render :show, status: :created, location: @order_menu_item }
      else
        format.html { render :new }
        format.json { render json: @order_menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_menu_items/1
  # PATCH/PUT /order_menu_items/1.json
  def update
    respond_to do |format|
      if @order_menu_item.update(order_menu_item_params)
        format.html { redirect_to @order_menu_item, notice: 'Order menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_menu_item }
      else
        format.html { render :edit }
        format.json { render json: @order_menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_menu_items/1
  # DELETE /order_menu_items/1.json
  def destroy
    @order_menu_item.destroy
    respond_to do |format|
      format.html { redirect_to order_menu_items_url, notice: 'Order menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_menu_item
      @order_menu_item = OrderMenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_menu_item_params
      params.require(:order_menu_item).permit(:order_id, :menu_item_id, :quantity)
    end
end

app/helpers/order_menu_items_helper.rb
module OrderMenuItemsHelper
end

app/views/order_menu_items/_form.html.erb
<%= form_with(model: order_menu_item, local: true) do |form| %>
  <% if order_menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_menu_item.errors.count, "error") %> prohibited this order_menu_item from being saved:</h2>

      <ul>
      <% order_menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :menu_item_id %>
    <%= form.text_field :menu_item_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_menu_items/edit.html.erb
<h1>Editing Order Menu Item</h1>

<%= render 'form', order_menu_item: @order_menu_item %>

<%= link_to 'Show', @order_menu_item %> |
<%= link_to 'Back', order_menu_items_path %>

app/views/order_menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Menu item</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_menu_items.each do |order_menu_item| %>
      <tr>
        <td><%= order_menu_item.order %></td>
        <td><%= order_menu_item.menu_item %></td>
        <td><%= order_menu_item.quantity %></td>
        <td><%= link_to 'Show', order_menu_item %></td>
        <td><%= link_to 'Edit', edit_order_menu_item_path(order_menu_item) %></td>
        <td><%= link_to 'Destroy', order_menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Menu Item', new_order_menu_item_path %>

app/views/order_menu_items/new.html.erb
<h1>New Order Menu Item</h1>

<%= render 'form', order_menu_item: @order_menu_item %>

<%= link_to 'Back', order_menu_items_path %>

app/views/order_menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_menu_item.order %>
</p>

<p>
  <strong>Menu item:</strong>
  <%= @order_menu_item.menu_item %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_menu_item.quantity %>
</p>

<%= link_to 'Edit', edit_order_menu_item_path(@order_menu_item) %> |
<%= link_to 'Back', order_menu_items_path %>